site_name: Zerto In-Cloud (ZIC) for Amazon Web Services (AWS) v1.1
theme:
  name: readthedocs
  highlightjs: false
nav:
- Prerequisites & Requirements: Prerequisites_&_Requirements.md
- ZIC Installation: ZIC_installation_components.md
- Deploying the ZIC Instance: Deploying_the_ZIC_Instance.md
- Configuring ZIC To Use Access Token from Keycloak: Use_access_token_from_keycloak.md
plugins:
- zerto_swagger
- search
markdown_extensions:
  - tables
  - admonition
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
